[package]
name = "d3"
version = "0.1.0"
authors = ["Bruce Brown <bruce_brown_1207@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## cargo clippy --all -- -W clippy::all -W clippy::pedantic -W clippy::restriction -W clippy::nursery -D warnings

[dependencies]
crossbeam = "0.7.3"
crossbeam-channel = "0.4.4"
smart-default = "0.6.0"
atomic_refcell = "0.1.6"

log = "0.4.11"
simplelog = "0.8.0"

d3-lib = {version = "0.1.0", path = "./d3-lib"}
d3-components =  {version = "0.1.0", path = "./d3-components"}
echo-server = {version = "0.1.0", path = "./echo-server"}
chat-server = {version = "0.1.0", path = "./chat-server"}
