edition = "2018"
max_width = 140
comment_width = 140
normalize_comments = true
normalize_doc_attributes = true
fn_single_line = true
inline_attribute_width = 100
match_block_trailing_comma = true
spaces_around_ranges = true
fn_args_layout = "Compressed"
#single_line_if_else_max_width = 100
report_todo = "Always"
report_fixme = "Always"
