#
# This development is `merged` with default, but not quite the way I'd like.
# Need to find a replacement config management tool. But for now, this 
# works well enough.
#
dev_mode = true
log_level = "Debug"
test_server_duration = 20

#
# Enable Forwarder feature to run daisy_chain nad fanout_fanin tests.
features = ["Forwarder"]
#services = []

[executor]
executors = 3
queue_size = 500
time_slice = 20

[[additional]]
[additional.Forwarder]
run = [
#    "daisy_chain",
#    "fanout_fanin",
#    "chaos_monkey",
]

[additional.Forwarder.default]
timeout = 30
machines = 100
messages = 20
iterations = 1
forwarding_multiplier = 1

[additional.Forwarder.daisy_chain]
timeout = 600
machines = 4000
messages = 100
forwarding_multiplier = 1
iterations = 10

[additional.Forwarder.fanout_fanin]
fanin_capacity = 500
machines = 400
messages = 1
iterations = 1
unbound_queue = 0


[additional.Forwarder.chaos_monkey]
#
# This will send ((inflection_value * 2) * messages) + messages + 1
# per iteration. The `+ messages + 1` accounts for notification messages
#
# during setup, each machine is sent a sender for every machine, including itself.
# For large tests, having a larger queue may reduce startup warnings, you use
# the unbound_queue option
#
timeout = 600
machines = 2000
messages = 100
inflection_value = 49
iterations = 1
unbound_queue = 1