name: CI Tests
#
# Run tests on Linux, Windows, and Mac using nightly.
#
on:
  push:
    branches-ignore:
      - master
      
jobs:
  build_matrix:
    name: Run tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      matrix:
        #name: [linux, windows, macos]
        name: [windows]
        include:
          - name: linux
            os: ubuntu-latest
            timeout: 30

          - name: windows
            os: windows-latest
            timeout: 45

          - name: macos
            os: macos-latest
            timeout: 30

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - uses: Swatinem/rust-cache@v1

    # install vcpkg and let it help with SDL2 dependencies -- see Cargo.toml
    - name: Install vcpkg
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build

    - name: Test
      run: cargo test --workspace --tests -- --test-threads 1
      env:
        RUST_BACKTRACE: full